# hArI NI kITA baKaL bElaJAr mATEMATik/SainS
by Balqis


In [1]:
import numpy as np

## variable sbgai array
![variable](variable.png)

In [14]:
nama = np.array(['hazirah','balqis','arissa','batrisyia', 'ayman'])
umur = np.array([25,11,10,14,16])
bulan = np.array([10,4,12,7,11])

In [5]:
umur

array([25, 11, 10, 14, 16])

In [6]:
umur[1]

11

In [7]:
nama[1]

'balqis'

In [8]:
bulan[2]

12

## 1. operasi matematik

In [9]:
bulan+umur # yg biasa

array([35, 15, 22, 21, 27])

In [10]:
np.add(bulan,umur) # guna numpy

array([35, 15, 22, 21, 27])

In [11]:
bulan*umur # darab

array([250,  44, 120,  98, 176])

In [13]:
np.multiply(bulan,umur, umur)

array([250,  44, 120,  98, 176])

## 2. fungsi

In [16]:
#umur.mean() # mean cara 1
np.mean(umur) # mean cara 2

15.2

In [17]:
#umur.min()
np.min(umur)

10

In [18]:
np.max(umur)

25

In [19]:
np.median(umur) #median

14.0

In [ ]:
10,11,14,16,25

In [20]:
(14+15)/2

14.5

In [21]:
this = np.array([10,11, 14, 15, 16, 25])
np.median(this)

14.5

## 3. numpy utk constant. cth pi

In [22]:
np.pi # np.sin np.cos

3.141592653589793